# Generated by Django 4.2.3 on 2023-07-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0003_alter_contributors_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='contributor_id',
            new_name='contributor',
        ),
    ]
