# Generated by Django 4.2.3 on 2023-07-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0006_issues_contributor_issues_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='proirity',
            new_name='priority',
        ),
    ]
