# Generated by Django 4.2.3 on 2023-07-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0007_rename_proirity_issues_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Issues', to='softdesk.contributors'),
        ),
    ]
