# Generated by Django 4.2.3 on 2023-07-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('softdesk', '0008_alter_issues_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('task', 'Task')], max_length=7)),
                ('statut', models.CharField(choices=[('todo', 'Todo'), ('inprogress', 'In progress'), ('finished', 'Finished')], default='todo', max_length=11)),
                ('issue_contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Issue_contributor', to='softdesk.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('backend', 'Back-end'), ('frontend', 'Front-end'), ('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('project_contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='issues',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='contributor',
        ),
        migrations.DeleteModel(
            name='Contributors',
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Issue_project', to='softdesk.project'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contributor_project', to='softdesk.project'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contributor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_issue', to='softdesk.issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_user', to='softdesk.contributor'),
        ),
    ]
