# Generated by Django 4.2.3 on 2023-07-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0011_alter_issue_description_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor_user',
            new_name='contributor_author',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_contributor',
            new_name='issue_author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_contributor',
            new_name='project_author',
        ),
    ]
