# Generated by Django 4.2.3 on 2023-07-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0019_rename_project_author_project_author_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='contributor_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_issue',
            new_name='issue_id',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor_project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor_author',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_author',
            new_name='contributor_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='user_id',
        ),
    ]
