# Generated by Django 4.2.3 on 2023-07-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0020_rename_comment_author_comment_contributor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contributor_id',
            new_name='contributor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='contributor_id',
            new_name='contributor',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
