# Generated by Django 4.2.3 on 2023-07-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0025_alter_contributor_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='author',
        ),
    ]
