# Generated by Django 4.2.3 on 2023-07-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0029_remove_comment_contributor_comment_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('title', 'project')},
        ),
    ]
