# Generated by Django 4.2.3 on 2023-07-18 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0031_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
