# Generated by Django 4.2.3 on 2023-07-20 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0035_rename_comment_uuid_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
