# Generated by Django 4.2.3 on 2023-07-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('softdesk', '0037_issue_assign_user_alter_issue_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assign_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
