# Generated by Django 4.2.3 on 2023-07-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0038_alter_issue_assign_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assign_user',
            new_name='assigned_user',
        ),
    ]
