# Generated by Django 4.2.3 on 2023-07-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0039_rename_assign_user_issue_assigned_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='user',
            new_name='author_user',
        ),
    ]
