# Generated by Django 4.2.3 on 2023-07-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0044_alter_issue_assigned_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
