# Generated by Django 4.2.3 on 2023-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_users_birthday_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(default=None),
        ),
    ]
