# Generated by Django 4.2.3 on 2023-07-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_users_first_name_remove_users_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
    ]
