# Generated by Django 4.2.3 on 2023-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_users_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateField(default=None),
        ),
    ]
